export const AppError = {
  USER_EXIST: 'User  with this email already exists',
  USER_NOT_EXIST: 'User with this email does not exist',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_TOKEN: 'Invalid token',
  USER_NOT_FOUND: 'User not found',
  WRONG_DATA: 'Wrong data',
  ASSET_NOT_FOUND: 'Asset not found',
  ASSETS_NOT_FOUND: 'Assets not found',
  ERROR_JWT: 'Error during validate JWT',
  ERROR_REGISTRATION: 'Error during register user',
  ADMIN_DELETE_USER: 'Remove user forbidden for your account',
  ASSET_ALREADY_EXISTS: 'Asset already exists',
  VERIFY_TOKEN_NOT_FOUND: 'Verify token not found',
};
