export const AppError = {
  USER_EXIST: 'User  with this email already exists',
  USER_CREATE_ERROR: 'Error create User',
  REGISTER_USER_ERROR: 'User registration failed',
  USER_NOT_EXIST: 'User with this email does not exist',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_NOT_FOUND: 'Token not found',
  USER_NOT_FOUND: 'User not found',
  WRONG_DATA: 'Wrong data',
  ASSET_NOT_FOUND: 'Asset not found',
  ASSETS_NOT_FOUND: 'Assets not found',
  ERROR_JWT: 'Error during validate JWT',
  ERROR_REGISTRATION: 'Error during register user',
  ADMIN_DELETE_USER: 'Remove user forbidden for your account',
  ASSET_ALREADY_EXISTS: 'Asset already exists',
  VERIFY_TOKEN_NOT_FOUND: 'Verify value not found',
  VERIFY_DOES_NOT_VERIFY: 'User needs to verify the account',
  ERROR_LOGIN_USER: 'Error during login database',
};
